"""empty message

Revision ID: 020399fde3a9
Revises: 54ea4d598d42
Create Date: 2024-12-02 12:28:21.604831

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '020399fde3a9'
down_revision = '54ea4d598d42'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('exercise',
    sa.Column('name', sa.String(length=500), nullable=False),
    sa.Column('muscle', sa.String(length=500), nullable=True),
    sa.Column('equipment', sa.String(length=500), nullable=True),
    sa.Column('video', sa.String(length=500), nullable=True),
    sa.PrimaryKeyConstraint('name')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('exercise')
    # ### end Alembic commands ###
