"""empty message

Revision ID: 6813ea40a8fd
Revises: 020399fde3a9
Create Date: 2024-12-02 21:16:03.136254

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6813ea40a8fd'
down_revision = '020399fde3a9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('workout',
    sa.Column('userEmail', sa.String(length=500), nullable=False),
    sa.Column('exerciseName', sa.String(length=500), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('sets', sa.Integer(), nullable=True),
    sa.Column('reps', sa.Integer(), nullable=True),
    sa.Column('weight', sa.Float(), nullable=True),
    sa.Column('difficulty', sa.Integer(), nullable=True),
    sa.Column('notes', sa.String(length=500), nullable=True),
    sa.ForeignKeyConstraint(['exerciseName'], ['exercise.name'], ),
    sa.ForeignKeyConstraint(['userEmail'], ['user.email'], ),
    sa.PrimaryKeyConstraint('userEmail', 'exerciseName', 'date')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('workout')
    # ### end Alembic commands ###
